name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Auth to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: https://ghcr.io
      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/p17-family/nginx:latest
          build-args: |
            NGINX_VERSION_ARG=stable
            H5BP_VERSION_ARG=latest
